### ISSUE TITLE
Adventurer's Pickaxe harvest levels

### ISSUE THREAD

**Issue by athenashavoc** [Necr0/ConvenientAdditions#6] opened 2016-12-30 21:56 UTC
Some blocks not registering the pickax's current mining level

[Tech Expansion mod](https://github.com/abused/Tech-Expansion ) with stone level pickaxe. Switching to vanilla stone pickaxe will allow me to mine.

![2016-12-30_13 20 36](https://cloud.githubusercontent.com/assets/1483940/21573067/34332a22-ce95-11e6-803f-ec6f673f09fb.png)

---

Also, I'm not sure if this is intentional but pickaxe will not harvest stairs, bricks, or furnaces (this is what I've encountered so far)

![2016-12-29_21 51 11](https://cloud.githubusercontent.com/assets/1483940/21573118/ace577c2-ce95-11e6-9900-ea880d160ff0.png)

**Comment by QbDesu** [comment] 2016-12-31 15:57
Thanks for reporting the bug. It will be fixed in the next version. Both issues were probably caused by the same bug. Unfortunately I do not maintain multiple versions at once which means this fix will only be released for 1.11.2+ builds. Sorry about that.

**Closed as completed by QbDesu** 2016-12-31 15:57 UTC
Labels: bug, 1.11
