### ISSUE TITLE
Double and triple jump not working

### ISSUE THREAD

**Issue by illumincrotty** [Necr0/ConvenientAdditions#17] opened 2017-03-19 21:05 UTC
Currently the double and triple jump baubles don't grant me double or triple jump. They increase jump height but don't allow extra jumps.

**Comment by QbDesu** [comment] 2017-03-19 23:26
Probably related to syncing problems. I'll look into it.

**Comment by QbDesu** [comment] 2017-03-20 16:51
Weird, looks like I'm not able to reproduce it even when running a dedicated server instance. Which is honestly what I expected because the jump is handled on both sides separately.

**Comment by QbDesu** [comment] 2017-03-20 17:00
Okay it seems to only be working in the debug environment.

**Comment by QbDesu** [comment] 2017-03-20 19:55
Alright, I figured it out. It should be fixed in v.1.2.3 which is currently waiting for approval.

**Comment by QbDesu** [comment] 2017-03-20 20:02
Nevermind, it still has some issues.

**Comment by QbDesu** [comment] 2017-03-20 20:34
Okay, waiting for approval. Should be up soon (for real this time). Worked out all the quirks.

**Closed as completed by QbDesu** 2017-03-20 20:34 UTC
Labels: bug, client, 1.11.2

**Comment by QbDesu** [comment] 2017-03-20 20:43
It's available now: https://minecraft.curseforge.com/projects/convenient-additions/files/2395518
I was able to fix it thanks to the help of SkySom on the #minecraftforge IRC, just to give proper credit.
