### ISSUE TITLE
Adventurer's Pickaxe's Veinminer Function Bug

### ISSUE THREAD

**Issue by ghost** [Necr0/ConvenientAdditions#8] opened 2017-01-10 17:34 UTC
my adventurer's pickaxe got veinminer ability. i broke a 2x2 iron ore; and i got only 2 iron ores! and also in diamond ores. veinminer mod doesn't give me the correct ore counts :((((
using minecraft 1.11.2 forge 13.20.0.2206 and latest mod version

**Comment by QbDesu** [comment] 2017-01-12 15:19
So the bug happens when using a vein mining pickaxe while the veinminer mod is installed. Do I understand that correctly?

**Comment by ghost** [comment] 2017-01-12 16:01
No you misunderstand. Veinminer option is already in your mod. Just take a diamond adventurers pickaxe, mine with it, and it will get veinminer option soon. And the problem that i said, will happen. Because i didn't installed a mod about vein mining.

**Comment by ghost** [comment] 2017-01-12 16:02
And i want to give an advice. Can you add the hexxit gear to your mod? Only hexxit flower, hexical diamond and 3 different hexxit armor sets :p it would be awesome. Thanks.

**Comment by QbDesu** [comment] 2017-01-12 16:30
I'm awfully sorry but I can't seem to reproduce any voiding of ores. It may have been an issue with desyncing if you are playing on a server. If that was the case it may be fixed in the next version.

Also, no, I will not add Hexical Gear to my mod. The reasons being 1. I don't own the mod and will not just copy/steal other mods, 2. the mod doesn't aim for such things, the mods purpose is to assist vanilla Minecraft and new tiers of tools or armor are not a part of that, hence the titanium ore which was placed in between iron and diamond was removed a while ago.

**Closed as completed by QbDesu** 2017-01-12 16:30 UTC
Labels: bug, 1.11.2
